route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
### Receiver gitlab
#  - name: gitlab
#    webhook_configs:
#      - http_config:
#          authorization:
#            type: Bearer
#            credentials: <credential>
#        send_resolved: true
#        url: 'https://gitlab.com/<groups>/<projects>/prometheus/alerts/notify.json'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']